# Generated by Django 6.0.4 on 2026-05-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('BET_CREATED', 'Apuesta Creada'), ('BET_SETTLED', 'Apuesta Liquidada'), ('WALLET_MOVEMENT', 'Movimiento de Wallet'), ('ODDS_CHANGED', 'Cambio de Cuotas')], max_length=20)),
                ('payload', models.JSONField(help_text='Datos del evento en formato JSON')),
                ('previous_hash', models.CharField(editable=False, max_length=64)),
                ('current_hash', models.CharField(editable=False, max_length=64)),
            ],
            options={
                'db_table': 'api_audit_log',
                'ordering': ['id'],
            },
        ),
    ]
