# Generated by Django 6.0.4 on 2026-05-29 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_triggered', models.CharField(choices=[('MULTIPLE_ACCOUNTS_SAME_IP', 'Misma IP con múltiples cuentas'), ('IDENTICAL_GROUP_BETTING', 'Patrón de apuestas idénticas en grupo'), ('IMMEDIATE_DEPOSIT_CASHOUT', 'Depósito inmediato seguido de Cash-Out')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], default='MEDIUM', max_length=10)),
                ('details', models.JSONField(help_text='Pruebas recolectadas (IPs, IDs de apuestas, marcas de tiempo)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('REVIEWED', 'Revisado / Confirmado'), ('DISMISSED', 'Descartado / Falso Positivo')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuario principal involucrado (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_suspicious_activity',
                'ordering': ['-created_at'],
            },
        ),
    ]
