# Generated by Django 6.0.4 on 2026-05-28 02:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100)),
                ('visitante', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_vivo', 'En Vivo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('anulado', 'Anulado')], default='programado', max_length=20)),
                ('goles_local', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('goles_visitante', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='1X2', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercados', to='betting.evento')),
            ],
            options={
                'verbose_name': 'Mercado',
                'verbose_name_plural': 'Mercados',
                'db_table': 'mercados',
            },
        ),
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cuota', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1.0001'))])),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='betting.mercado')),
            ],
            options={
                'verbose_name': 'Selección',
                'verbose_name_plural': 'Selecciones',
                'db_table': 'selecciones',
            },
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.1000'))])),
                ('cuota_fijada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('estado', models.CharField(choices=[('accepted', 'Aceptada'), ('won', 'Ganada'), ('lost', 'Perdida'), ('cancelled', 'Cancelada')], default='accepted', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuestas', to=settings.AUTH_USER_MODEL)),
                ('seleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuestas', to='betting.seleccion')),
            ],
            options={
                'verbose_name': 'Apuesta',
                'verbose_name_plural': 'Apuestas',
                'db_table': 'apuestas',
                'ordering': ['-creado'],
            },
        ),
    ]
