# Generated by Django 6.0.4 on 2026-05-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='tipo',
            field=models.CharField(choices=[('SIMPLE', 'Simple'), ('COMBINADA', 'Combinada')], default='SIMPLE', max_length=15),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='seleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apuestas_simples', to='betting.seleccion'),
        ),
        migrations.CreateModel(
            name='ApuestaSeleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota_fijada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('apuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='betting.apuesta')),
                ('seleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='betting.seleccion')),
            ],
            options={
                'verbose_name': 'Detalle de Apuesta',
                'verbose_name_plural': 'Detalles de Apuesta',
                'db_table': 'apuestas_selecciones',
                'unique_together': {('apuesta', 'seleccion')},
            },
        ),
        migrations.AddField(
            model_name='apuesta',
            name='selecciones',
            field=models.ManyToManyField(related_name='apuestas', through='betting.ApuestaSeleccion', to='betting.seleccion'),
        ),
    ]
