# Generated by Django 6.0.4 on 2026-05-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_apuesta_tipo_alter_apuesta_seleccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='minuto_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='periodo',
            field=models.CharField(default='1T', max_length=20),
        ),
    ]
