# Generated by Django 6.0.4 on 2026-05-29 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_evento_minuto_actual_evento_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='evento',
            unique_together={('local', 'visitante', 'fecha_inicio')},
        ),
        migrations.AddField(
            model_name='evento',
            name='local_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_local', to='betting.equipo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='visitante_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_visitante', to='betting.equipo'),
        ),
    ]
