# Generated by Django 6.0.4 on 2026-05-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_equipo_alter_evento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='estado',
            field=models.CharField(choices=[('accepted', 'Aceptada'), ('cashed_out', 'Retirada'), ('won', 'Ganada'), ('lost', 'Perdida'), ('cancelled', 'Cancelada')], default='accepted', max_length=20),
        ),
    ]
