# Generated by Django 6.0.4 on 2026-05-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0005_alter_apuesta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercado',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
