# Generated by Django 6.0.4 on 2026-05-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0006_mercado_resuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='usar_bono',
            field=models.BooleanField(default=False, help_text='Indica si la apuesta fue realizada con saldo de bono'),
        ),
    ]
