# Generated by Django 6.0.4 on 2026-05-26 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('estado', models.CharField(choices=[('pendiente_verificacion', 'Pendiente Verificación'), ('verificado', 'Verificado'), ('bloqueado', 'Bloqueado'), ('autoexcluido', 'Autoexcluido')], default='pendiente_verificacion', max_length=30)),
                ('limite_deposito_diario', models.DecimalField(decimal_places=4, default=1000.0, max_digits=18)),
                ('limite_deposito_semanal', models.DecimalField(decimal_places=4, default=5000.0, max_digits=18)),
                ('limite_deposito_mensual', models.DecimalField(decimal_places=4, default=20000.0, max_digits=18)),
                ('tipo_autoexclusion', models.CharField(choices=[('ninguna', 'Ninguna'), ('7_dias', '7 días'), ('30_dias', '30 días'), ('90_dias', '90 días'), ('indefinida', 'Indefinida')], default='ninguna', max_length=20)),
                ('fecha_autoexclusion_hasta', models.DateTimeField(blank=True, null=True)),
                ('limite_pendiente', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('tipo_limite_pendiente', models.CharField(blank=True, choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=20, null=True)),
                ('fecha_solicitud_incremento', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
