# Generated by Django 6.0.5 on 2026-05-30 00:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('betting', '0006_mercado_resuelto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('bienvenida', 'Bono de Bienvenida'), ('recarga', 'Bono de Recarga'), ('manual', 'Bono Manual (Operador)')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rollover_multiplier', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Veces que debe apostarse el monto antes de retirar', max_digits=4)),
                ('rollover_requerido', models.DecimalField(decimal_places=4, help_text='monto * rollover_multiplier', max_digits=10)),
                ('rollover_apostado', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('cuota_minima_rollover', models.DecimalField(decimal_places=4, default=Decimal('1.5000'), help_text='Cuota mínima para que una apuesta cuente al rollover', max_digits=5)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('expirado', 'Expirado'), ('revocado', 'Revocado por Abuso')], default='activo', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('expira', models.DateTimeField(blank=True, help_text='Fecha de expiración del bono', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='AlertaAbuso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('risk_free', 'Apuesta Sin Riesgo'), ('matched_betting', 'Matched Betting'), ('arbitrage', 'Arbitraje')], max_length=20)),
                ('detalle', models.JSONField(default=dict, help_text='Detalles técnicos de la detección (apuestas involucradas, coberturas, etc.)')),
                ('revisado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_abuso', to=settings.AUTH_USER_MODEL)),
                ('bono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='panel.bono')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='BonoApuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_aportado', models.DecimalField(decimal_places=4, help_text='Monto de la apuesta que cuenta para el rollover', max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('apuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos_asociados', to='betting.apuesta')),
                ('bono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas', to='panel.bono')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddIndex(
            model_name='bono',
            index=models.Index(fields=['usuario', 'estado'], name='panel_bono_usuario_663c18_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaabuso',
            index=models.Index(fields=['revisado', 'creado'], name='panel_alert_revisad_15c722_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bonoapuesta',
            unique_together={('bono', 'apuesta')},
        ),
    ]
