# Generated by Django 6.0.4 on 2026-05-30 03:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoBono',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Código promocional único', max_length=50, unique=True)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rollover_multiplier', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Multiplicador de rollover para el bono', max_digits=4)),
                ('usos_maximos', models.IntegerField(help_text='Cantidad máxima de usuarios que pueden canjearlo')),
                ('usos_actuales', models.IntegerField(default=0, help_text='Cantidad de canjes realizados')),
                ('expira', models.DateTimeField(help_text='Fecha de expiración obligatoria')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='bono',
            name='codigo_bono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonos_redimidos', to='panel.codigobono'),
        ),
    ]
