# Generated by Django 6.0.4 on 2026-05-27 03:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.CharField(choices=[('wallet_usuario', 'Billetera Usuario'), ('casa', 'Cuenta Casa'), ('apuestas_pendientes', 'Apuestas Pendientes'), ('bonos', 'Bonos'), ('cashout', 'Cash-Out')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('direction', models.CharField(choices=[('DEBIT', 'Débito'), ('CREDIT', 'Crédito')], max_length=10)),
                ('transaction_id', models.UUIDField(db_index=True)),
                ('tipo_transaccion', models.CharField(choices=[('deposito', 'Depósito'), ('retiro', 'Retiro'), ('apuesta', 'Apuesta'), ('liquidacion_ganada', 'Liquidación Ganada'), ('liquidacion_perdida', 'Liquidación Perdida'), ('cashout', 'Cash-Out'), ('cancelacion', 'Cancelación'), ('bono', 'Bono'), ('ajuste', 'Ajuste')], max_length=30)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado_en', 'id'],
                'indexes': [models.Index(fields=['user', 'account', 'creado_en'], name='wallet_ledg_user_id_9ba26f_idx'), models.Index(fields=['transaction_id'], name='wallet_ledg_transac_a947a0_idx')],
            },
        ),
    ]
