# Generated by Django 6.0.4 on 2026-05-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='cuenta',
            field=models.CharField(choices=[('wallet_usuario', 'Billetera del Usuario'), ('casa', 'Casa de Apuestas'), ('apuestas_pendientes', 'Apuestas Pendientes'), ('bonos', 'Bonos'), ('bonos_usuario', 'Bonos del Usuario')], max_length=30, verbose_name='Cuenta'),
        ),
    ]
